name: Provision Infrastructure Test

on:
  push:
    branches:
      - "main" 
    paths:
      - "Bicep/**"
      - ".github/workflows/bicepTest.yml"
  workflow_dispatch:

jobs:
  provision-service-bus:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Provision Resources
      uses: azure/arm-deploy@v1
      id: deploy
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        scope: resourcegroup
        template: ./Bicep/staticwebapp.v3.bicep
        failOnStdErr: false
        deploymentName: bicep-test-ci

    - name: Run script file
      env:
        APIKey: ${{ secrets.APIKey }}
        ZoneId: ${{ secrets.ZoneId }}
        HostName: ${{ steps.deploy.outputs.defaultHostname }}
      run: ./Bicep/dns.ps1
      shell: pwsh

    - name: Set Custom Domain
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        scope: resourcegroup
        template: ./Bicep/staticwebapp.v4.bicep
        failOnStdErr: false
        deploymentName: bicep-test-ci
