name: Provision Infrastructure

on:
  push:
    branches:
      - "main" 
    paths:
      - "Bicep/**"
      - ".github/workflows/bicep.yml"
  workflow_dispatch:

jobs:
  provision-service-bus:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        scope: resourcegroup
        template: ./Bicep/main.bicep
        failOnStdErr: false
        deploymentName: bicep-ci
        deploymentMode: Complete
