name: Provision Infrastructure

on:
  push:
    branches:
      - "main" 
    paths:
      - "Bicep/**"
      - ".github/workflows/bicep.yml"
  workflow_dispatch:

jobs:
  provision-service-bus:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Empty Out Environment
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ vars.AZURE_RG }}
        scope: resourcegroup
        template: ./Bicep/empty.bicep
        failOnStdErr: false
        deploymentName: empty-bicep-ci
        deploymentMode: Complete

    - name: Provision Resources
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ vars.AZURE_RG }}
        scope: resourcegroup
        template: ./Bicep/main.bicep
        parameters: serviceBusNamespaceName=${{ vars.RESOURCE_NAME }}sb storageAccountName=${{ vars.RESOURCE_NAME }}sa appServicePlanName=${{ vars.RESOURCE_NAME }}asp functionAppName=${{ vars.RESOURCE_NAME }}func webAppName=${{ vars.RESOURCE_NAME }}web
        failOnStdErr: false
        deploymentName: bicep-ci
        deploymentMode: Complete
